services:
  duckdns:
    image: lscr.io/linuxserver/duckdns
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - SUBDOMAINS={{domain}}
      - TOKEN={{token}}
      - LOG_FILE=false
    volumes:
      - duckdns:/config

variables:
  - token
