services:
  homeassistant:
    image: lscr.io/linuxserver/homeassistant
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - homeassistant:/config

ingresses:
  homeassistant: 8123