services:
  keycloak:
    image: quay.io/keycloak/keycloak
    environment:
      - KEYCLOAK_ADMIN={{username}}
      - KEYCLOAK_ADMIN_PASSWORD={{password}}
    command: start-dev
    volumes:
      - keycloak:/opt/keycloak/data



ingresses:
  keycloak: 8080