services:
  readarr:
    image: lscr.io/linuxserver/readarr:develop
    volumes:
      - readarr:/config
      - media:/data
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Stockholm

ingresses:
  readarr: 8787