services:
  sabnzbd:
    image: lscr.io/linuxserver/sabnzbd
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - sabnzbd:/config
      - media:/data

ingresses:
  sabnzbd: 8080
