services:
  sonarr:
    image: lscr.io/linuxserver/sonarr
    volumes:
      - sonarr:/config
      - media:/data
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Stockholm

ingresses:
  sonarr: 8989