services:
  unifi:
    image: lscr.io/linuxserver/unifi-controller
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - unifi:/config
    ports:
      - 3478:3478/udp
      - 10001:10001/udp
      - 8080:8080
ingresses:
  unifi:
    port: 8443
    protocol: https